export { StartGame } from './startgane';
export { Game } from './chat';
export { ReviewList } from './reviews';
export { PageNotFound } from './page-not-found';
export { Leaderboard } from './leaderboard';
export { Words } from './words';
export { ProfileInfo } from './profile/info';
export { ProfileScores } from './profile/scores';
export { LoginPage, action as LoginAction } from './auth/Login';
export { RegisterPage, action as RegisterAction } from './auth/Register';
